spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/robot_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    filters: wall,mergeStat
  flyway:
    baselineVersion: 0
    cleanDisabled: true
    outOfOrder: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    enabled: true
    table: flyway_schema
#多数据源情况的配置
robot:
  muti-datasource:
    open: false
    url: jdbc:mysql://127.0.0.1:3306/guns_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    dataSourceNames:
    - dataSourceRobot
    - dataSourceBiz